name: clip-snap-paint # you probably want to 'snapcraft register <name>'
title: Clip Studio Paint
base: core18 # the base snap is the execution environment for this snap
version: "1.9.11" # just for humans, typically '1.2+git' or '1.3.2'
summary: Bottled Clip Studio Paint installation for linux # 79 char long summary
description: |
  Clip Studio Paint installator under wine, mostly functional!
  Known issues:
  - Window does not play nice with most window managers, which may result in ghost programs open or problems when maximizing.
  - No online features: Activation, assets store, or any other feature that requires access to Celsys servers is non functional.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

environment:
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES"
  SOMMELIER_STRICT: "1" # Make Sommelier exit when unset variable is used. (useful to find bugs in sommelier)
  TRICKS: "fontfix corefonts win10 vcrun2010 vcrun2019"
apps:
  clip-snap-paint:
    extensions: [gnome-3-28]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "C:/Program Files/CELSYS/CLIP STUDIO 1.5/CLIP STUDIO PAINT/CLIPStudioPaint.exe"
      INSTALL_URL: "https://vd.clipstudio.net/clipcontent/paint/app/1911/CSP_1911w_setup.exe"
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups-control
      - cups
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [gnome-3-28]
    command: bin/sommelier
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups-control
      - cups
  # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [gnome-3-28]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git

# These plugs are used to connect the snap to the wine runtime.
plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-6-staging:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-6-staging
